feat: load theme and darkmode from ASF Storage
JustArchiNET/ASF-ui pull request #1575
Opened 2022-06-22 06:47 UTC by yuyinws

## Description

Related: #1572  #1431

Becase of theme preferences is stored in browser cache, so when user clean their brower cache,theme preferences will be lose.
The solution is to also store the theme preferences into the ASF cache(/API/Storage). That is what this PR did.
## Screenshots

![image](https://s2.loli.net/2022/06/22/c3byhIuo4Vp8Jqa.png)
Theme preferences also take effect when there is no relevant data in the browser cache
## Additional information

## Checklist

- [x] My pull request is not a duplicate
- [x] I added a descriptive title to this pull request
- [x] I added a concise description or a self-explanatory screenshot to this pull request
- [x] My code follows the code style of this project
- [x] I have performed a self-review of my own code

2022-06-22 09:41 UTC, Aareksio requested changes
Splendid! Great PR! Thank you very much!

I am not entirely sure whether overriding remote settings with local ones on each client load is a good idea, but this is not a blocker by any means. Please check the comment regarding async init. 

As `storage` grows it'd be a good idea to add some abstraction to force logic architecture. It may get hard to maintain quickly if we start adding more and more variables to single init function. TODO for later.

2022-06-22 09:41 UTC, Aareksio commented on src/store/modules/storage.js
> +  },
`init` in `storage` is async and waits for HTTP call before setting theme from `localStorage`. This may lead to flash of wrong (blue) theme when asf-ui is accessed on remote not local machine. 

Could you please load the theme from localStorage first, then attempt network override?

2022-06-22 09:41 UTC, Aareksio commented on src/store/modules/storage.js
> +  },
Why is the variable `_theme` underscore prefixed?

2022-06-22 12:07 UTC, yuyinws commented
@Aareksio 
Hi, I had modify the `Storage` init logic. Now it will be load theme config from local. And if remote config is available, local config will be overwritten. I think this way is better.

Please review again, thanks!

2022-06-23 07:29 UTC, Aareksio requested changes

2022-06-23 07:29 UTC, Aareksio commented on src/store/modules/storage.js
> +      if (asfDarkmode) commit('setDarkMode', asfDarkmode);
Now you are overriding local settings with remote

```suggestion
      // get and set config from ASF
      // local config will be overwritten if ASF config is available
      const response = await http.get('/storage/asfui-settings');
      const { theme: asfTheme, darkMode: asfDarkmode } = response;
      if (!localTheme && asfTheme) commit('changeTheme', asfTheme);
      if (!darkMode && asfDarkmode) commit('setDarkMode', asfDarkmode);
```

2022-06-23 07:36 UTC, Aareksio commented on src/store/modules/storage.js
> +      if (asfDarkmode) commit('setDarkMode', asfDarkmode);
Imagine we have 2 clients that connect to ASF-ui, we'll force them to use the same theme and dark mode settings, along with a flash of incorrect theme each time they visit. 

Local > Remote (previous):
- if 2nd client connects, it uses the same theme as 1st client (blue)
- if 2nd client changes theme (red), 1st client keeps old one (blue)
- if 3rd client connects, it uses the most recently changed theme (red)
- no matter how many times clients visit page, their preferred theme is kept, no action of a client affects other, already configured clients

Remote > Local (current):
- if 2nd client connects, it uses the same theme as 1st client (blue)
- if 2nd client changes theme (red), 1st client also changes theme (red) **!!**
- if 3rd client connects, it uses the most recently changed theme (red)
- with each reload, 1st client sees a flash of their preferred theme (blue) replaced by _global_ theme (red); in fact the worst case scenario all buy one client see flashes and wrong theme on each visit

2022-06-23 07:39 UTC, Aareksio commented on src/store/modules/storage.js
> +      if (asfDarkmode) commit('setDarkMode', asfDarkmode);
@JustArchi @MrBurrBurr @SuperSandro2000 Which approach do you think is better? Single ASF theme, or per-client configuration with initial state defaulting to latest change?

2022-06-23 08:15 UTC, Abrynos commented on src/store/modules/storage.js
> +      if (asfDarkmode) commit('setDarkMode', asfDarkmode);
I personally would go with single ASF theme.

2022-06-23 08:39 UTC, JustArchi commented on src/store/modules/storage.js
> +      if (asfDarkmode) commit('setDarkMode', asfDarkmode);
Considering the fact that ASF's IPC is meant for a single user exclusively, I'd go with single theme to not overcomplicate. Several people can already use several ASF instances, and there is very little motivation to design whole IPC permissions system to make it viable to have multiple-users configuration, moreover, it'd require far too many changes in core aspects of how ASF works, so I don't see it happening anytime soon, and probably never at all.

2022-06-23 09:09 UTC, Aareksio approved these changes

2022-06-23 10:45 UTC, merged

2022-06-23 10:46 UTC, MrBurrBurr commented
Thank you for your PR 🎉 

Closes #1431 
Closes #1572

2022-06-23 10:49 UTC, JustArchi commented
@MrBurrBurr Did you guys ensure initial setup when user is asked for password? ASF will refuse you access to storage endpoint without a valid password, so you should ensure call to storage happens afterwards, not before.

I didn't test this code in practice, so maybe it's already covered, just highlighting it.

2022-06-23 12:03 UTC, Aareksio commented
It should silently break on initial load and download server settings upon reload. Furthermore, this should break the website when user attempts to update theme before logging in, as this executes http call to protected route. I am positive the browser can handle it and only display an error in console, but we should fix nonetheless